# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(blank=True, max_length=100, null=True), max_length=100, null=True, unique=True),
        ),
    ]
